### ISSUE TITLE
issue with spark_read_bigquery

### ISSUE THREAD

**Issue by paullevchuk** [miraisolutions/sparkbq#13]
In documentation there is an error - you CANNOT use service account file via parameter `serviceAccountKeyFile`. 

Thanks to Javier Luraschi (from RStudio), he figured out that correct code from example should be like this:
```
hamlet <- 
  spark_read_bigquery(
    sc,
    name = "hamlet",
    billingProjectId = <your_project_id>,
    type = "direct",
    gcsBucket = <your_bucket>,
    projectId = "publicdata",
    datasetId = "samples",
    tableId = "shakespeare",
    additionalParameters = list(bq.service_account_key_file = <your_key_filepath_and_name>)
)
```

Please take into account that if you use `type` = "direct", then temporary dataset "spark_staging_US" will be created and content of table/query will be placed in temporary table inside that dataset.

If you do NOT have "*.create" permissions, then specify `type` = "csv" and `gcsBucket` = <your_bucket> to avoid writing to GBQ.

**Comment by spoltier** [comment]
Thank you! I was able to test your proposed changes successfully and I'm updating the doc. Another way to provide the service account key is to set the environment variable `GOOGLE_APPLICATION_CREDENTIALS`, that is
```
Sys.setenv(GOOGLE_APPLICATION_CREDENTIALS=<your_key_filepath_and_name>)
```
This way you don't need to provide the `additionalParameters` on every call.
It would be great if you can let me know if that method works as well for you.

**Comment by paullevchuk** [comment]
I did quick test of proposed by you last solution with environment var `GOOGLE_APPLICATION_CREDENTIALS`. 

It does NOT work for me... Here is what I got:

```
Error: shadegoogle.cloud.bigquery.BigQueryException: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
	at shadegoogle.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:99)
	at shadegoogle.cloud.bigquery.spi.v2.HttpBigQueryRpc.getDataset(HttpBigQueryRpc.java:110)
	at shadegoogle.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:263)
	at shadegoogle.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:260)
	at shadegoogle.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at shadegoogle.cloud.RetryHelper.run(RetryHelper.java:74)
	at shadegoogle.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at shadegoogle.cloud.bigquery.BigQueryImpl.getDataset(BigQueryImpl.java:260)
	at com.miraisolutions.spark.bigquery.client.BigQueryClient.getOrCreateDataset(BigQueryClient.scala:104)
	at com.miraisolutions.spark.bigquery.client.BigQueryClient.getOrCreateStagingDataset(BigQueryClient.scala:121)
	at com.miraisolutions.spark.bigquery.client.BigQueryClient.createTemporaryTableReference(BigQueryClient.scala:142)
	at com.miraisolutions.spark.bigquery.client.BigQueryClient.executeQuery(BigQueryClient.scala:198)
	at com.miraisolutions.spark.bigquery.DefaultSource$$anonfun$com$miraisolutions$spark$bigquery$DefaultSource$$sqlTableOpt$1$1.apply(DefaultSource.scala:173)
	at com.miraisolutions.spark.bigquery.DefaultSource$$anonfun$com$miraisolutions$spark$bigquery$DefaultSource$$sqlTableOpt$1$1.apply(DefaultSource.scala:172)
	at scala.Option.map(Option.scala:146)
	at com.miraisolutions.spark.bigquery.DefaultSource$.com$miraisolutions$spark$bigquery$DefaultSource$$sqlTableOpt$1(DefaultSource.scala:172)
	at com.miraisolutions.spark.bigquery.DefaultSource$$anonfun$getBigQueryTableReference$2.apply(DefaultSource.scala:176)
	at com.miraisolutions.spark.bigquery.DefaultSource$$anonfun$getBigQueryTableReference$2.apply(DefaultSource.scala:176)
	at scala.Option.orElse(Option.scala:289)
	at com.miraisolutions.spark.bigquery.DefaultSource$.getBigQueryTableReference(DefaultSource.scala:176)
	at com.miraisolutions.spark.bigquery.DefaultSource$.com$miraisolutions$spark$bigquery$DefaultSource$$withBigQueryClient(DefaultSource.scala:200)
	at com.miraisolutions.spark.bigquery.DefaultSource.createRelation(DefaultSource.scala:47)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Unknown Source)
Caused by: shadegoogle.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
{
  "code" : 401,
  "errors" : [ {
    "domain" : "global",
    "location" : "Authorization",
    "locationType" : "header",
    "message" : "Login Required.",
    "reason" : "required"
  } ],
  "message" : "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
  "status" : "UNAUTHENTICATED"
}
	at shadegoogle.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at shadegoogle.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at shadegoogle.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at shadegoogle.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at shadegoogle.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at shadegoogle.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at shadegoogle.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at shadegoogle.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at shadegoogle.cloud.bigquery.spi.v2.HttpBigQueryRpc.getDataset(HttpBigQueryRpc.java:108)
	... 58 more
> 
```

**Comment by spoltier** [comment]
@paullevchuk I think my comment may have been a bit misleading. The most reliable way to set the variable is before the R session starts using `export` or another mechanism (the updated README is more accurate). Otherwise it may not take effect.
In any case, your and Javier's proposed solution is now the primary one documented in the README.

**Comment by spoltier** [comment]
Update: I had a quick look at the code, and was able to fix it to match the intent of the original documentation. The `serviceAccountKeyFile` parameter now works.
