### ISSUE TITLE
Spark write to BigQuery throws IllegalArgumentException: invalid method bigquery

### ISSUE THREAD

**Issue by pcejrowski** [miraisolutions/sparkbq#8]
Reading from BQ works perfectly fine for me. However, I've got some problems with writing to BQ.
I run this code: 
```
iris_tbl <- copy_to(sc, iris, overwrite = TRUE)
spark_write_bigquery(
  data = iris_tbl,
  projectId = "my-project",
  datasetId = "my-dataset",
  tableId = "my-table",
  name = "my-name",
  mode = "overwrite")
```
and I'm getting the following error:
```
Error: java.lang.IllegalArgumentException: invalid method bigquery for object 157
	at sparklyr.Invoke$.invoke(invoke.scala:122)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

Traceback:

1. spark_write_bigquery(data = iris_tbl, projectId = "my-project", 
 .     datasetId = "my-dataset", tableId = "my-table", name = "my-name", 
 .     mode = "overwrite")
2. spark_write_source(data, source = "bigquery", mode = mode, options = parameters, 
 .     ...)
3. spark_write_source.tbl_spark(data, source = "bigquery", mode = mode, 
 .     options = parameters, ...)
4. spark_data_write_generic(sqlResult, name, source, mode, options, 
 .     partition_by)
5. invoke(options, fileMethod, path)
6. invoke.shell_jobj(options, fileMethod, path)
7. invoke_method(spark_connection(jobj), FALSE, jobj, method, ...)
8. invoke_method.spark_shell_connection(spark_connection(jobj), 
 .     FALSE, jobj, method, ...)
9. core_invoke_method(sc, static, object, method, ...)
10. withr::with_options(list(warning.length = 8000), {
  .     if (nzchar(msg)) {
  .         core_handle_known_errors(sc, msg)
  .         stop(msg, call. = FALSE)
  .     }
  .     else {
  .         msg <- core_read_spark_log_error(sc)
  .         stop(msg, call. = FALSE)
  .     }
  . })
11. force(code)
12. stop(msg, call. = FALSE)
```

PS. Great thanks to the authors -- reading BQ works fine and it saved a lot of my time.

**Comment by martinstuder** [comment]
Just to make sure, did you upgrade to the current version of sparklyr from github? sparklyr 0.6.4 won't work due to an issue with `spark_write_source` used by `spark_write_bigquery`. We probably have to state that more prominently in the README.

**Comment by pcejrowski** [comment]
That's correct. 
Thank you very much!
